import Link from "next/link";
import { SiteHeader } from "@/components/SiteHeader";

/**
 * Real terms copy. This is version "v1" — the wizard sends that fixed
 * string with the application submission (see TERMS_VERSION in
 * app/get-started/page.tsx). Bump that constant, and the "Last updated"
 * line below, whenever this copy materially changes.
 */
const LAST_UPDATED = "1 August 2026";

export default function TermsPage() {
  return (
    <>
      <SiteHeader />

      <main className="page-wide">
        <p className="eyebrow">Legal</p>
        <h1>Terms of Service</h1>
        <p className="subtitle">Version 1 &middot; Last updated {LAST_UPDATED}</p>

        <section className="docs-section" style={{ paddingTop: 0 }}>
          <h2>1. Agreement</h2>
          <p>
            These terms govern access to and use of HoBS (&ldquo;the
            Service&rdquo;) by hotels, guesthouses, and similar hospitality
            businesses (&ldquo;you&rdquo;, &ldquo;the merchant&rdquo;). By
            submitting an application through the onboarding wizard,
            signing in, or using the dashboard, you agree to be bound by
            these terms. If you&rsquo;re accepting on behalf of a business,
            you confirm you&rsquo;re authorised to do so.
          </p>
        </section>

        <section className="docs-section">
          <h2>2. The Service</h2>
          <p>
            HoBS lets guests check room availability, receive a price, and
            pay for a stay through WhatsApp, and gives you and your staff a
            dashboard to manage rooms, room types, bookings, and staff
            activity. We may add, change, or remove features over time, and
            will make reasonable efforts to notify you of changes that
            materially reduce functionality you rely on.
          </p>
        </section>

        <section className="docs-section">
          <h2>3. Applying and onboarding</h2>
          <p>
            Access to the dashboard is granted after we review your
            application. You&rsquo;re responsible for the accuracy of the
            information you submit, including contact details, business
            details, and the identity information used for verification
            (CAC number, BVN, or NIN). We may decline an application, or
            suspend or terminate access later, if information turns out to
            be false, misleading, or if verification fails.
          </p>
          <p>
            We use the identity information you provide solely to verify
            who you are and that the business is genuine. It does not
            affect your application while it&rsquo;s under manual review,
            and it&rsquo;s handled under the same protections described in
            Section 7.
          </p>
        </section>

        <section className="docs-section">
          <h2>4. Accounts, staff, and security</h2>
          <p>
            Once approved, you&rsquo;ll receive an email to set a password
            for the merchant account. You can invite staff to sign in
            separately with their own credentials; every action a staff
            member takes is recorded in the audit log, and a top manager can
            review, revert, or change staff roles. You&rsquo;re responsible
            for keeping your login credentials confidential and for
            activity that happens under your account or your staff&rsquo;s
            accounts. Tell us immediately if you suspect unauthorised
            access.
          </p>
        </section>

        <section className="docs-section">
          <h2>5. Bookings and payments</h2>
          <p>
            Guests pay through a secure payment link generated by the
            Service; a booking is only marked confirmed once payment is
            received. You&rsquo;re responsible for honouring confirmed
            bookings at the price and terms quoted to the guest, and for
            keeping room availability and pricing in the dashboard
            accurate, since that&rsquo;s what HoBS quotes to guests on
            WhatsApp. Any fees charged for use of the Service or for
            payment processing will be disclosed to you separately (for
            example during onboarding or in your merchant agreement) before
            they apply.
          </p>
        </section>

        <section className="docs-section">
          <h2>6. Acceptable use</h2>
          <p>You agree not to:</p>
          <ul className="docs-feature-list">
            <li>
              Use the Service to take payment for bookings you don&rsquo;t
              intend to honour, or to misrepresent rooms, pricing, or
              availability to guests.
            </li>
            <li>
              Attempt to access another merchant&rsquo;s hotel, bookings,
              or dashboard data without authorisation.
            </li>
            <li>
              Interfere with or disrupt the Service, including attempting
              to bypass rate limits, authentication, or the staff
              role/audit-log controls.
            </li>
            <li>
              Use the Service for any unlawful purpose, or in a way that
              violates the rights of guests or third parties.
            </li>
          </ul>
        </section>

        <section className="docs-section">
          <h2>7. Data and privacy</h2>
          <p>
            We collect the business, contact, and verification information
            you submit during onboarding, plus booking and dashboard
            activity generated through ordinary use, in order to run the
            Service, verify merchants, prevent fraud, and provide support.
            We don&rsquo;t sell your data or your guests&rsquo; data. We
            retain the audit log and booking records for as long as
            reasonably needed for the purposes above and to meet legal
            obligations.
          </p>
        </section>

        <section className="docs-section">
          <h2>8. Suspension and termination</h2>
          <p>
            You may stop using the Service at any time. We may suspend or
            terminate access to the dashboard or WhatsApp booking flow for
            a hotel if these terms are breached, if verification
            information can&rsquo;t be confirmed, if required by law, or to
            protect the Service or its users from harm. Where practical,
            we&rsquo;ll give notice and a chance to resolve the issue
            first.
          </p>
        </section>

        <section className="docs-section">
          <h2>9. Liability</h2>
          <p>
            The Service is provided on an &ldquo;as is&rdquo; basis. To the
            extent permitted by law, HoBS isn&rsquo;t liable for indirect
            or consequential losses arising from use of the Service, such
            as lost bookings or lost profits, except where such loss
            results from our own negligence, wilful misconduct, or breach
            of these terms.
          </p>
        </section>

        <section className="docs-section">
          <h2>10. Changes to these terms</h2>
          <p>
            We may update these terms as the Service evolves. Material
            changes will be reflected in the version number and
            &ldquo;last updated&rdquo; date above, and where an application
            or agreement referenced a specific version, that&rsquo;s the
            version that applies to it.
          </p>
        </section>

        <section className="docs-section" style={{ borderBottom: "1px solid var(--line)" }}>
          <h2>11. Contact</h2>
          <p>
            Questions about these terms, or about an application currently
            under review, can be sent to our team by email or WhatsApp using
            the contact details provided during onboarding.
          </p>
        </section>
      </main>

      <footer className="site-footer">
        <span>&copy; {new Date().getFullYear()} HoBS</span>
        <div className="site-footer-links">
          <Link href="/">Home</Link>
          <Link href="/docs">Docs</Link>
        </div>
      </footer>
    </>
  );
}
