"""add hotel domain models

Revision ID: 417fc089cb11
Revises: 0021_credential_verified
Create Date: 2026-07-25

Hand-written, NOT autogenerated. The autogenerate run picked up a large
amount of unrelated drift on the original ShoprHQ tables (dropped unique
constraints, a dropped column on webhook_events, column comment diffs) --
none of that belongs in a migration whose job is "add the hotel tables."
This migration touches ONLY room_types, rooms, room_bookings, and
hotel_staff, and nothing else in the database.
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '417fc089cb11'
down_revision = '0021_credential_verified'
branch_labels = None
depends_on = None


def upgrade():
    # ── room_types ──────────────────────────────────────────────────────
    op.create_table(
        'room_types',
        sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column('name', sa.String(255), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('price', sa.Float(), nullable=False),
        sa.Column('image_url', sa.String(500), nullable=True),
        sa.Column('merchant_id', sa.String(20), nullable=False),
        sa.Column('client_id', sa.String(20), nullable=False),
        sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    )
    op.create_index('ix_room_types_client', 'room_types', ['client_id'])
    op.create_index('ix_room_types_merchant_id', 'room_types', ['merchant_id'])

    # ── rooms ───────────────────────────────────────────────────────────
    op.create_table(
        'rooms',
        sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column('room_number', sa.String(20), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.Column('merchant_id', sa.String(20), nullable=False),
        sa.Column('client_id', sa.String(20), nullable=False),
        sa.Column('room_type_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['room_type_id'], ['room_types.id'], ondelete='RESTRICT'),
        sa.UniqueConstraint('client_id', 'room_number', name='uq_room_number_per_hotel'),
    )
    op.create_index('ix_rooms_client', 'rooms', ['client_id'])
    op.create_index('ix_rooms_room_type', 'rooms', ['room_type_id'])
    op.create_index('ix_rooms_merchant_id', 'rooms', ['merchant_id'])

    # ── room_bookings ───────────────────────────────────────────────────
    booking_status_enum = postgresql.ENUM(
        'CREATED', 'PENDING_PAYMENT', 'PAID', 'CHECKED_IN',
        'CHECKED_OUT', 'CANCELLED', 'REFUNDED',
        name='booking_status',
        create_type=False,  # we create it explicitly below -- without this,
                            # create_table() tries to create it AGAIN on its
                            # own and fails with "type already exists"
    )
    booking_source_enum = postgresql.ENUM(
        'guest_whatsapp', 'staff_whatsapp', 'dashboard',
        name='booking_source',
        create_type=False,
    )
    booking_status_enum.create(op.get_bind(), checkfirst=True)
    booking_source_enum.create(op.get_bind(), checkfirst=True)

    op.create_table(
        'room_bookings',
        sa.Column('id', sa.String(36), primary_key=True),
        sa.Column('booking_code', sa.String(8), nullable=False, unique=True),
        sa.Column('merchant_id', sa.String(20), nullable=False),
        sa.Column('client_id', sa.String(20), nullable=False),
        sa.Column('room_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('guest_name', sa.String(100), nullable=True),
        sa.Column('guest_phone', sa.String(20), nullable=True),
        sa.Column('check_in', sa.Date(), nullable=False),
        sa.Column('check_out', sa.Date(), nullable=False),
        sa.Column('total_amount', sa.Numeric(12, 2), nullable=False),
        sa.Column('amount_paid', sa.Numeric(12, 2), nullable=True),
        sa.Column('payment_ref', sa.String(100), nullable=True),
        sa.Column('status', booking_status_enum, nullable=False, server_default='CREATED'),
        sa.Column('source', booking_source_enum, nullable=False, server_default='guest_whatsapp'),
        sa.Column('logged_by_staff_phone', sa.String(20), nullable=True),
        sa.Column('raw_staff_message', sa.Text(), nullable=True),
        sa.Column('reminder_sent_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('metadata', postgresql.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('checked_in_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('checked_out_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='RESTRICT'),
    )
    op.create_index('ix_bookings_merchant_client', 'room_bookings', ['merchant_id', 'client_id'])
    op.create_index('ix_bookings_room_dates', 'room_bookings', ['room_id', 'check_in', 'check_out'])
    op.create_index('ix_bookings_status', 'room_bookings', ['status'])
    op.create_index('ix_bookings_created_at', 'room_bookings', ['created_at'])
    op.create_index('ix_bookings_code_lookup', 'room_bookings', ['booking_code', 'merchant_id'])
    op.create_index('ix_room_bookings_merchant_id', 'room_bookings', ['merchant_id'])
    op.create_index('ix_room_bookings_client_id', 'room_bookings', ['client_id'])
    op.create_index('ix_room_bookings_room_id', 'room_bookings', ['room_id'])
    op.create_index('ix_room_bookings_guest_phone', 'room_bookings', ['guest_phone'])
    op.create_index('ix_room_bookings_payment_ref', 'room_bookings', ['payment_ref'])

    # ── hotel_staff ─────────────────────────────────────────────────────
    op.create_table(
        'hotel_staff',
        sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column('name', sa.String(100), nullable=True),
        sa.Column('phone_number', sa.String(20), nullable=False),
        sa.Column('role', sa.String(20), nullable=False, server_default='front_desk'),
        sa.Column('password_hash', sa.String(255), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.Column('merchant_id', sa.String(20), nullable=False),
        sa.Column('client_id', sa.String(20), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
        sa.UniqueConstraint('client_id', 'phone_number', name='uq_staff_phone_per_hotel'),
    )
    op.create_index('ix_hotel_staff_phone', 'hotel_staff', ['phone_number'])
    op.create_index('ix_hotel_staff_merchant_id', 'hotel_staff', ['merchant_id'])
    op.create_index('ix_hotel_staff_client_id', 'hotel_staff', ['client_id'])


def downgrade():
    op.drop_table('hotel_staff')
    op.drop_table('room_bookings')
    op.execute('DROP TYPE IF EXISTS booking_status')
    op.execute('DROP TYPE IF EXISTS booking_source')
    op.drop_table('rooms')
    op.drop_table('room_types')