"""add staff permission system

Revision ID: a8f3d21c9e04
Revises: 417fc089cb11
Create Date: 2026-07-27

Hand-written, not autogenerated -- same reasoning as 417fc089cb11: keeps
this migration scoped to exactly what changed (one new column on
hotel_staff, two new tables) rather than picking up unrelated drift on
the inherited ShoprHQ tables.
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'a8f3d21c9e04'
down_revision = '417fc089cb11'
branch_labels = None
depends_on = None


def upgrade():
    # ── hotel_staff.email ───────────────────────────────────────────────
    op.add_column('hotel_staff', sa.Column('email', sa.String(255), nullable=True))

    # ── staff_action_logs ───────────────────────────────────────────────
    op.create_table(
        'staff_action_logs',
        sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column('merchant_id', sa.String(20), nullable=False),
        sa.Column('client_id', sa.String(20), nullable=False),
        sa.Column('staff_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('staff_phone_snapshot', sa.String(20), nullable=False),
        sa.Column('room_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('booking_id', sa.String(36), nullable=True),
        sa.Column('action', sa.String(30), nullable=False),
        sa.Column('previous_status', sa.String(30), nullable=True),
        sa.Column('new_status', sa.String(30), nullable=True),
        sa.Column('raw_message', sa.Text(), nullable=True),
        sa.Column('is_high_impact', sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column('reviewed', sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column('reviewed_by_staff_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('reverted', sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column('reverted_by_log_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('revert_code', sa.String(8), nullable=True),
        sa.Column('revert_expires_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['staff_id'], ['hotel_staff.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['reviewed_by_staff_id'], ['hotel_staff.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['booking_id'], ['room_bookings.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['reverted_by_log_id'], ['staff_action_logs.id'], ondelete='SET NULL'),
    )
    op.create_index('ix_staff_action_logs_merchant_id', 'staff_action_logs', ['merchant_id'])
    op.create_index('ix_staff_action_logs_client_id', 'staff_action_logs', ['client_id'])
    op.create_index('ix_action_logs_hotel_created', 'staff_action_logs', ['client_id', 'created_at'])
    op.create_index('ix_action_logs_staff', 'staff_action_logs', ['staff_id'])
    op.create_index('ix_action_logs_review_pending', 'staff_action_logs', ['client_id', 'reviewed'])
    op.create_index('ix_staff_action_logs_revert_code', 'staff_action_logs', ['revert_code'])

    # ── permission_change_requests ──────────────────────────────────────
    op.create_table(
        'permission_change_requests',
        sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column('merchant_id', sa.String(20), nullable=False),
        sa.Column('client_id', sa.String(20), nullable=False),
        sa.Column('requested_by_staff_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('target_staff_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('old_role', sa.String(20), nullable=False),
        sa.Column('new_role', sa.String(20), nullable=False),
        sa.Column('code', sa.String(6), nullable=False),
        sa.Column('email_sent_to', sa.String(255), nullable=False),
        sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('attempts', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['requested_by_staff_id'], ['hotel_staff.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['target_staff_id'], ['hotel_staff.id'], ondelete='CASCADE'),
    )
    op.create_index('ix_permission_change_requests_merchant_id', 'permission_change_requests', ['merchant_id'])
    op.create_index('ix_permission_change_requests_client_id', 'permission_change_requests', ['client_id'])
    op.create_index('ix_permission_requests_pending', 'permission_change_requests', ['client_id', 'confirmed_at'])


def downgrade():
    op.drop_table('permission_change_requests')
    op.drop_table('staff_action_logs')
    op.drop_column('hotel_staff', 'email')
